// Route data distilled from "Spain advice from Annette.docx" + the date-anchored plan (Oct 2027).
// Frame: depart Sydney Wed 29/Thu 30 Sep 2027 · on the ground Fri 1 Oct · Bamberg finale Tue 19–Thu 21 Oct · fly Frankfurt→Sydney Fri 22 Oct · land Sun 24 Oct.
// One direction only: Paris → La Rochelle → coast → Bilbao → Rioja, then Bamberg as the final stop
// before flying home from Frankfurt. No backtracking, and the beer comes last.
// Each stop: id, chapter, name, sub, coords, zoom, dates (anchored), nights, leg, wiki (photo),
// desc, annette (verbatim-ish), highlights [{title, url, note, cost}], booking, cost, tags.

const maps = (q) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;

export const CHAPTERS = {
  prologue: 'Prologue',
  france: 'Côte Atlantique',
  basqueFr: 'Pays Basque · France',
  basqueEs: 'Euskadi · Spain',
  rioja: 'La Rioja',
  franconia: 'Franken · Germany',
  epilogue: 'Epilogue',
};

export const STOPS = [
  {
    id: 'paris',
    chapter: 'prologue',
    name: 'Paris',
    sub: 'Land, sleep it off, keep moving',
    coords: [48.8566, 2.3522],
    zoom: 5,
    dates: 'Fri 1 Oct',
    nights: '1',
    leg: 'fly',
    wiki: 'Paris',
    wikiExtra: ['Eiffel Tower', 'Louvre'],
    desc: 'Overnight flight from Sydney (depart Wed 29 or Thu 30 Sep), boots on the ground Friday 1 October. One recovery night in Paris, then fly (or train) to La Rochelle on Saturday morning. Bamberg now waits at the far end of the trip — no more zig-zag across Europe on day two.',
    annette: 'Stations are dodgy in every country, especially Spain and France. Be careful.',
    highlights: [
      { title: 'Eiffel Tower at dusk', url: maps('Eiffel Tower'), note: 'jet-lag walk: Trocadéro → tower → Seine', cost: 'free from the ground' },
      { title: 'Louvre courtyard & Tuileries', url: 'https://www.louvre.fr/en/', note: 'even without going in, the evening lap resets the body clock', cost: 'entry ~€22 if keen' },
      { title: 'SNCF Connect', url: 'https://www.sncf-connect.com/en-en/', note: 'book the Paris legs early — fares roughly double close to travel', cost: '' },
      { title: 'Google Flights: SYD→PAR', url: 'https://www.google.com/travel/flights', note: 'price the long-haul as soon as leave is approved', cost: 'return ~A$1,600–2,500 pp' },
    ],
    booking: 'Submit the leave estimate (29/30 Sep → 22 Oct), then book long-haul — 3–5 months out is the sweet spot for October.',
    cost: 'Airport hotel or Marais cheapie €120–180 · dinner €30–50 pp',
    tags: ['transit', 'recovery night'],
  },
  {
    id: 'iledere',
    chapter: 'france',
    name: 'La Rochelle & Île de Ré',
    sub: 'Pick up the car. Oysters, posh, pricey.',
    coords: [46.1958, -1.4266],
    zoom: 10,
    dates: 'Sat 2 Oct',
    nights: '1',
    leg: 'fly',
    wiki: 'Île de Ré',
    wikiExtra: ['La Rochelle', 'Phare des Baleines'],
    desc: 'Fly into La Rochelle Saturday morning and collect the rental — big enough for everyone and their bags, small enough for coastal roads. Cross the bridge to Île de Ré: whitewashed villages, bikes everywhere, serious oysters. The soft spot of the plan — priciest and most optional; drop it and Royan still covers oysters.',
    annette: 'Popular holiday destination, mad oysters, very posh, very $$$.',
    highlights: [
      { title: 'Saint-Martin-de-Ré harbour', url: maps('Saint-Martin-de-Ré port'), note: 'Vauban-walled harbour town — lunch on the quay', cost: 'seafood lunch €25–40 pp' },
      { title: 'Oyster shacks, Île de Ré', url: maps('degustation huitres Ile de Re'), note: 'oysters + cold white at a producer shack', cost: 'dozen €14–22' },
      { title: 'La Rochelle Old Port & towers', url: maps('Vieux Port La Rochelle'), note: 'the three medieval harbour towers, right by the car pickup', cost: 'towers ~€10' },
      { title: 'Phare des Baleines', url: maps('Phare des Baleines Ile de Re'), note: 'lighthouse at the island’s tip — climb it for the full sweep', cost: '~€4' },
    ],
    booking: 'Rental: book France pickup now. Cross-border car fee — France pickup with Bilbao drop-off usually carries a one-way international charge. Check it, or plan to return the car in France.',
    cost: 'Bridge toll ~€8 off-season · island hotels €150+/night — the €€€ stop',
    tags: ['decision: drop it?', 'car pickup', 'oysters', 'posh'],
  },
  {
    id: 'royan',
    chapter: 'france',
    name: 'South of Royan',
    sub: 'Huge, fresh, flavour-loaded oysters',
    coords: [45.6285, -1.0281],
    zoom: 9,
    dates: 'Sun 3 Oct',
    nights: '1',
    leg: 'drive',
    wiki: 'Royan',
    wikiExtra: ['Talmont-sur-Gironde', 'Marennes-Hiers-Brouage'],
    desc: 'Drive south to the mouth of the Gironde. The reason to come is simple: fantastic oysters — huge, fresh and flavourful. Set your baseline here; you will be comparing every plate for the rest of the trip.',
    annette: 'Fantastic oysters. Huge, fresh and flavourful.',
    highlights: [
      { title: 'Marennes-Oléron oyster cabanes', url: maps('degustation huitres Marennes-Oléron'), note: 'the appellation just south of Royan — eat at a producer’s shack', cost: 'dozen €12–20' },
      { title: 'La Cayenne port, Marennes', url: maps('Port de la Cayenne Marennes'), note: 'row of tasting cabins on the channel', cost: '' },
      { title: 'Talmont-sur-Gironde', url: maps('Talmont-sur-Gironde'), note: 'clifftop village with the 12th-c church hanging over the estuary — 15 min south', cost: 'free' },
      { title: 'Brouage citadel', url: maps('Brouage citadelle'), note: 'star-shaped fortress town stranded in the marshes', cost: 'free' },
    ],
    booking: 'Walk-in. Cabanes keep short hours off-season — aim for lunch.',
    cost: 'Oyster lunch €15–30 pp · hotels €80–120/night',
    tags: ['oysters', 'coast'],
  },
  {
    id: 'bordeaux',
    chapter: 'france',
    name: 'Bordeaux',
    sub: 'Wine region, castles, big lunches',
    coords: [44.8378, -0.5792],
    zoom: 8,
    dates: 'Mon 4 – Tue 5 Oct',
    nights: '2',
    leg: 'drive',
    wiki: 'Bordeaux',
    wikiExtra: ['Place de la Bourse', 'Dune of Pilat'],
    desc: 'Best wine region on the planet, and castles everywhere. All of France is expensive, but the locals actually holiday on this coast — great food, wine and culture. Skip the South of France: mad expensive, marketed well, not actually authentic.',
    annette: 'Bordeaux — best wine region on the planet, lots of castles.',
    highlights: [
      { title: 'Cité du Vin', url: 'https://www.laciteduvin.com/en', note: 'the wine museum — good half-day primer before the châteaux', cost: '~€22' },
      { title: 'Médoc château tastings', url: maps('Chateau Margaux Medoc'), note: 'most châteaux need a booked visit; Margaux/Pauillac route', cost: '€15–40 pp per tasting' },
      { title: 'Saint-Émilion', url: maps('Saint-Emilion'), note: 'medieval wine village 40 min east — the "castles" fix', cost: 'free to wander' },
      { title: 'Place de la Bourse & Miroir d’eau', url: maps('Miroir d\'eau Bordeaux'), note: 'the mirror-pool reflection shot at dusk', cost: 'free' },
      { title: 'Dune du Pilat', url: maps('Dune du Pilat'), note: 'Europe’s tallest sand dune, 1 h west by Arcachon — pair with Arcachon oysters', cost: 'parking ~€6' },
    ],
    booking: 'Château visits must be reserved days–weeks ahead (their websites or Rue des Vignerons). Book accommodation with parking, always.',
    cost: 'Hotels €100–180/night · tastings €15–40 · big lunch €40–60 pp',
    tags: ['wine', 'castles'],
  },
  {
    id: 'hossegor',
    chapter: 'france',
    name: 'Capbreton & Hossegor',
    sub: 'Surf-comp season, head-sized mussels',
    coords: [43.655, -1.427],
    zoom: 11,
    dates: 'Wed 6 – Thu 7 Oct',
    nights: '2',
    leg: 'drive',
    wiki: 'Soorts-Hossegor',
    wikiExtra: ['Capbreton'],
    desc: 'The big surf spot on the French Atlantic. October comp windows run ~10 days, so midweek heats are common — and if the 2027 WSL dates make the weekend unmissable, swap these days with Bordeaux. Summery holiday vibes even as the season cools.',
    annette: 'Big spot for surfers. Surf comps in October bring culture, people, music. More oysters — and mussels the size of your head.',
    highlights: [
      { title: 'World Surf League schedule', url: 'https://www.worldsurfleague.com/events', note: 'check the France comp window against 6–7 Oct — free to watch from the beach', cost: 'free' },
      { title: 'Port de Capbreton oyster shacks', url: maps('degustation huitres Capbreton port'), note: 'oysters and giant mussels on the marina', cost: '€20–35 pp' },
      { title: 'La Gravière beach', url: maps('La Graviere Hossegor'), note: 'the famous heavy beach break — comp venue', cost: 'free' },
      { title: 'Capbreton estacade', url: maps('Estacade Capbreton'), note: 'the wooden pier and lighthouse — sunset walk over the Gouf canyon', cost: 'free' },
      { title: 'Lac d’Hossegor', url: maps('Lac d\'Hossegor'), note: 'tidal lake loop with oyster bars on the east shore', cost: 'free' },
    ],
    booking: 'If the comp lands on this weekend, book accommodation the moment WSL confirms dates — town fills.',
    cost: 'Hotels €90–150/night · seafood €25–40 pp',
    tags: ['surf', 'weekend', 'mussels'],
  },
  {
    id: 'bayonne',
    chapter: 'basqueFr',
    name: 'Bayonne',
    sub: 'Where Basque country begins',
    coords: [43.4929, -1.4748],
    zoom: 11,
    dates: 'Fri 8 – Sat 9 Oct',
    nights: 'base for 2',
    leg: 'drive',
    wiki: 'Bayonne',
    wikiExtra: ['Bayonne Cathedral'],
    desc: 'Two nights covering the French Basque coast: Bayonne, Biarritz and Saint-Jean-de-Luz are all 20 minutes apart. The area around Bayonne is much better culturally to explore than the glossier resorts — history, half-timbered streets, ham and chocolate.',
    annette: 'The area around Bayonne — history, much better culturally to explore. Hétéroclito restaurant: book a table in advance, try sunset.',
    highlights: [
      { title: 'Hétéroclito', url: maps('Heteroclito restaurant Bayonne'), note: 'THE Annette pick — book ahead, aim for sunset', cost: 'dinner €40–60 pp' },
      { title: 'Bayonne ham & chocolate crawl', url: maps('Rue Port Neuf Bayonne'), note: 'Rue Port-Neuf chocolate houses + jambon de Bayonne', cost: '€10–20' },
      { title: 'Petit Bayonne old quarter', url: maps('Petit Bayonne'), note: 'half-timbered streets between the rivers', cost: 'free' },
      { title: 'Bayonne Cathedral & cloister', url: maps('Cathedrale Sainte-Marie Bayonne'), note: 'UNESCO gothic on the Camino route', cost: 'free (cloister ~€2)' },
      { title: 'Musée Basque', url: maps('Musee Basque Bayonne'), note: 'the primer on everything Basque you’re about to eat and see', cost: '~€8' },
    ],
    booking: 'Hétéroclito: reserve several days ahead, ask for an outside table near sunset — lock it for Fri 8 or Sat 9 Oct.',
    cost: 'Hotels €90–140/night · dinner €40–60 pp',
    tags: ['history', 'culture', '2-night base'],
  },
  {
    id: 'cheese',
    chapter: 'basqueFr',
    name: 'The Cheese Hills',
    sub: 'Bidarray · Louhossoa · Cambo-les-Bains',
    coords: [43.302, -1.371],
    zoom: 10,
    dates: 'en route, 8–9 Oct',
    nights: 'day detour',
    leg: 'drive',
    wiki: 'Cambo-les-Bains',
    wikiExtra: ['Espelette', 'Bidarray'],
    desc: 'Inland detour off the coast days, technically still France. Sheep-farm country where every farmer runs their own flock — the source of Ossau-Iraty, Agour and neighbours of Comté-class quality. Stop, taste, fill the boot. Across the border, Idiazabal has its own signature cheese too.',
    annette: 'Cheese near the border, in France technically — stop on the coast drive. Agour, excellent cheeses. Around Bidarray, Louhossoa, Cambo-les-Bains — mad cheeses.',
    highlights: [
      { title: 'Fromagerie Agour, Hélette', url: maps('Fromagerie Agour Helette'), note: 'the Agour dairy — shop and tastings', cost: 'cheese €20–28/kg' },
      { title: 'Ossau-Iraty farm route', url: maps('Ossau-Iraty ferme Bidarray'), note: 'farm-gate signs between Bidarray and Cambo — just pull over', cost: '' },
      { title: 'Espelette', url: maps('Espelette'), note: 'the pepper village — façades strung with drying red peppers', cost: 'free (pepper jars €5–10)' },
      { title: 'Villa Arnaga, Cambo', url: maps('Villa Arnaga Cambo-les-Bains'), note: 'Edmond Rostand’s Basque mansion and gardens', cost: '~€9' },
    ],
    booking: 'No bookings — carry cash for farm gates.',
    cost: 'Budget €30–60 for the boot-full of cheese',
    tags: ['cheese', 'detour'],
  },
  {
    id: 'biarritz',
    chapter: 'basqueFr',
    name: 'Biarritz',
    sub: 'Markets, txuleta, the lighthouse walk',
    coords: [43.4832, -1.5586],
    zoom: 12,
    dates: 'Fri 8 – Sat 9 Oct',
    nights: 'day trip',
    leg: 'drive',
    wiki: 'Biarritz',
    wikiExtra: ['Rocher de la Vierge', 'Biarritz Lighthouse'],
    desc: 'Fancy shops up front, but the real Biarritz is at Les Halles market — a great spot for market food, and the surrounding streets near Place Sobradiel are where locals actually eat. Then walk the coastline from the Phare de Biarritz lighthouse down to Le Surfing, and go inside.',
    annette: 'Bar Jean Biarritz — the ones on the left and right are still good. Beef txuleta: pricey but good, like fancy. Basque fish and meat is basic but top quality.',
    highlights: [
      { title: 'Les Halles de Biarritz', url: maps('Les Halles de Biarritz'), note: 'the market — graze here, mornings till ~14:00', cost: '€10–20 grazing' },
      { title: 'Bar Jean', url: maps('Bar Jean Biarritz'), note: 'the classic next to the market; txuleta pricey but worth it', cost: 'txuleta €50–70 pp' },
      { title: 'Phare de Biarritz → Le Surfing walk', url: maps('Phare de Biarritz'), note: 'coastline walk south, finish inside Le Surfing', cost: 'free (lunch €25–40)' },
      { title: 'Rocher de la Vierge', url: maps('Rocher de la Vierge Biarritz'), note: 'the wave-battered footbridge to the Virgin’s rock — Biarritz’s postcard', cost: 'free' },
      { title: 'Grande Plage & Hôtel du Palais', url: maps('Grande Plage Biarritz'), note: 'the imperial beachfront built for Napoleon III’s empress', cost: 'free' },
    ],
    booking: 'Bar Jean: go before 13:00 for lunch or book dinner ahead.',
    cost: 'Big meal out €40–70 pp',
    tags: ['market', 'txuleta', 'coastal walk'],
  },
  {
    id: 'sjdl',
    chapter: 'basqueFr',
    name: 'Saint-Jean-de-Luz',
    sub: 'Picturesque, Basque as f***',
    coords: [43.3887, -1.6591],
    zoom: 12,
    dates: 'Sun 10 Oct, en route',
    nights: 'half-day',
    leg: 'drive',
    wiki: 'Saint-Jean-de-Luz',
    wikiExtra: ['Ciboure'],
    desc: 'The non-negotiable stop, timed as the last morning in France. A perfect fishing-port postcard of red-shuttered Basque houses around a sheltered bay. Wander, eat, photograph — then drive straight on to San Sebastián.',
    annette: 'DEFINITELY go to Saint-Jean-de-Luz. Literally picturesque, Basque as f***. Go straight to San Sebastián from there.',
    highlights: [
      { title: 'Maison Adam', url: maps('Maison Adam Saint-Jean-de-Luz'), note: 'macarons since 1660 — the box for the car', cost: '~€10–15' },
      { title: 'Grillerie du Port', url: maps('Grillerie du Port Saint-Jean-de-Luz'), note: 'grilled sardines/tuna right on the port (seasonal)', cost: 'lunch €20–35 pp' },
      { title: 'Église Saint-Jean-Baptiste', url: maps('Eglise Saint-Jean-Baptiste Saint-Jean-de-Luz'), note: 'where Louis XIV married — the door was walled up after', cost: 'free' },
      { title: 'Ciboure & Socoa fort', url: maps('Fort de Socoa Ciboure'), note: 'across the bay: Ravel’s birthplace and the harbour fort', cost: 'free' },
    ],
    booking: 'Nothing to book — it’s a wander-and-eat stop.',
    cost: 'Half-day: €30–50 pp all in',
    tags: ['must-see', 'postcard'],
  },
  {
    id: 'sansebastian',
    chapter: 'basqueEs',
    name: 'San Sebastián',
    sub: 'Monte Igueldo first, then the old town',
    coords: [43.3183, -1.9812],
    zoom: 12,
    dates: 'Sun 10 – Tue 12 Oct',
    nights: '3',
    leg: 'drive',
    wiki: 'San Sebastián',
    wikiExtra: ['Urgull', 'Peine del Viento'],
    desc: 'Three nights is more than enough. Go first to the Parque de Atracciones on Monte Igueldo — a dodgy, hectic old amusement park with the best view of the bay. The old town is worth exploring but overrated: more tourists than locals. Hit the fish market, drink txakoli in the morning, and find a sagardotegi in the mountains — ask locals, go to the most remote one.',
    annette: 'MUST try as many tomato salads as possible in Basque country in October. Basque country has the best cheesecake on the planet. Txakoli sagardotegi — EXCELLENT food, must eat and drink there.',
    highlights: [
      { title: 'Monte Igueldo funicular & park', url: 'https://www.monteigueldo.es/', note: 'go first — the best view of the bay from the creaky old rides', cost: 'funicular ~€4.50, rides €2–3' },
      { title: 'La Viña', url: maps('La Vina San Sebastian'), note: 'the burnt Basque cheesecake origin story', cost: 'slice ~€6' },
      { title: 'Bretxa fish market', url: maps('Mercado de la Bretxa San Sebastian'), note: 'the fish market Stuart says to hit', cost: 'free to wander' },
      { title: 'Remote mountain sagardotegi', url: maps('sagardotegia Gipuzkoa'), note: 'cider-house feast — ask locals, pick the most remote one', cost: 'set feast €40–50 pp' },
      { title: 'La Concha promenade', url: maps('Playa de la Concha San Sebastian'), note: 'the full crescent walk, railings and all — one of the world’s great city beaches', cost: 'free' },
      { title: 'Peine del Viento', url: maps('Peine del Viento San Sebastian'), note: 'Chillida’s wind combs bolted into the rocks at the bay’s west end', cost: 'free' },
      { title: 'Monte Urgull & the old fort', url: maps('Monte Urgull San Sebastian'), note: 'the other hill — castle, Christ statue, harbour views', cost: 'free' },
    ],
    booking: 'Sagardotegi: call a day or two ahead (classic season is Jan–Apr, so confirm October hours). Pintxos bars: no bookings, just crawl.',
    cost: 'Hotels €130–220/night · pintxos crawl €30–50 pp · txakoli €2.5–3.5/glass',
    tags: ['3 nights', 'txakoli', 'cheesecake', 'pintxos'],
  },
  {
    id: 'orio',
    chapter: 'basqueEs',
    name: 'Orio & Zarautz',
    sub: 'Grill smoke on the coast road',
    coords: [43.2805, -2.148],
    zoom: 12,
    dates: 'Wed 13 Oct',
    nights: 'lunch stop',
    leg: 'drive',
    wiki: 'Zarautz',
    wikiExtra: ['Getaria (Gipuzkoa)'],
    desc: 'Wednesday 13th starts the four-night coast run to Bilbao — coast road, NOT the highway, booking small-town hotels as you drive. First stop: Orio, home of Bodegón Asador Joxe Mari, a Stuart-endorsed temple of whole fish over coals. Zarautz next door is the walk-it-off beach stroll.',
    annette: 'Stuart says go to: Bodegón Asador Joxe Mari in Orio. Zarautz is nice. Get a small car and drive the coast road line, not the highway.',
    highlights: [
      { title: 'Bodegón Asador Joxe Mari', url: maps('Bodegon Joxe Mari Orio'), note: 'whole wild turbot/sea bream over coals on the river', cost: 'whole fish €50–70 pp' },
      { title: 'Zarautz beach promenade', url: maps('Zarautz beach'), note: 'the walk-it-off stroll; txakoli vineyards on the hill behind', cost: 'free' },
      { title: 'Getaria & Balenciaga Museum', url: maps('Cristobal Balenciaga Museoa Getaria'), note: 'the fishing village next door: Balenciaga’s couture museum + Elkano’s grilled turbot if Joxe Mari is full', cost: 'museum ~€10' },
      { title: 'Getaria–Zarautz clifftop path', url: maps('Getaria Zarautz coastal path'), note: '40-min walk between the two towns above the sea', cost: 'free' },
    ],
    booking: 'Joxe Mari: call ahead for Wednesday lunch — fish is sold by weight, confirm price when ordering.',
    cost: 'The one big-ticket lunch: €50–80 pp with wine',
    tags: ['asador', 'coast road'],
  },
  {
    id: 'lekeitio',
    chapter: 'basqueEs',
    name: 'Lekeitio → Mundaka',
    sub: 'Don’t stop between',
    coords: [43.3649, -2.5043],
    zoom: 11,
    dates: 'Wed 13 – Thu 14 Oct',
    nights: '1–2',
    leg: 'drive',
    wiki: 'Lekeitio',
    wikiExtra: ['Mundaka', 'Guernica'],
    desc: 'The prettiest stretch of the drive. From Lekeitio go straight to Mundaka without stopping between — Mundaka is a beautiful town on the Urdaibai estuary, home of one of the best left-hand waves in the world. Book hotels in random small coastal towns as you go; that slack is built into these four nights.',
    annette: 'From Lekeitio straight to Mundaka, don’t stop between. Mundaka is a beautiful town. Give us time to book hotels in random small towns on the coast.',
    highlights: [
      { title: 'Lekeitio harbour', url: maps('Lekeitio puerto'), note: 'grilled fish at whichever harbour bar has smoke coming out', cost: 'lunch €20–35 pp' },
      { title: 'Mundaka rivermouth wave', url: maps('Mundaka surf spot'), note: 'watch the famous left from the church terrace if a swell is running', cost: 'free' },
      { title: 'San Nicolás island, Lekeitio', url: maps('Isla de San Nicolas Lekeitio'), note: 'walk out across the seabed at low tide', cost: 'free' },
      { title: 'Gernika (Guernica)', url: maps('Casa de Juntas Gernika'), note: '10 min off-route: the Basque assembly house, the Tree, and the Picasso story', cost: 'free' },
      { title: 'Portuondo & the Gernika tables (local list)', url: 'food.html#ll-traditional-cooking', note: 'Asador Portuondo in Mundaka; Remenetxe, 1000 Colorau and Baserri Maitea ❤ in Gernika', cost: '€30–60 pp' },
      { title: 'Urdaibai estuary viewpoints', url: maps('Urdaibai mirador'), note: 'the biosphere reserve the coast road threads through', cost: 'free' },
    ],
    booking: 'Book same-day/next-day on Booking.com as you drive — small-town pensións rarely sell out in October.',
    cost: 'Pensións €70–110/night · seafood dinners €25–40 pp',
    tags: ['coast road', 'surf', 'estuary'],
  },
  {
    id: 'bermeo',
    chapter: 'basqueEs',
    name: 'Bermeo & Gaztelugatxe',
    sub: 'The Game of Thrones one',
    coords: [43.4445, -2.784],
    zoom: 12,
    dates: 'Fri 15 Oct',
    nights: 'half-day',
    leg: 'drive',
    wiki: 'Gaztelugatxe',
    wikiExtra: ['Bermeo'],
    desc: 'Just past Bermeo the hermitage of San Juan de Gaztelugatxe zig-zags out to sea on a stone causeway — Dragonstone, if you watched Game of Thrones. Definitely go if you like that landscape. Bermeo itself is a proper working fishing port.',
    annette: 'Definitely go to Bermeo if you like a Game of Thrones landscape.',
    highlights: [
      { title: 'San Juan de Gaztelugatxe', url: maps('San Juan de Gaztelugatxe'), note: '241 steps out and back — free timed ticket often required, ~1 km walk from the car park', cost: 'free (ticket required)' },
      { title: 'Bermeo canneries', url: maps('conservas Bermeo'), note: 'tinned bonito del norte and anchovies for the boot', cost: '€5–15/tin' },
      { title: 'Skura — sushi in Bermeo (local list)', url: 'food.html#ll-sushi-ramen-japanese', note: 'top value-for-quality per the insider list — the curveball lunch option', cost: '€25–40 pp' },
      { title: 'Bermeo old port', url: maps('Puerto Viejo Bermeo'), note: 'stacked painted fishermen’s houses around the working harbour', cost: 'free' },
      { title: 'Matxitxako lighthouse', url: maps('Cabo Matxitxako faro'), note: 'the cape between Bermeo and Gaztelugatxe — whale-watch point', cost: 'free' },
    ],
    booking: 'Gaztelugatxe: reserve the free entry slot on the Biscay tourism site a few days ahead — enforced in peak periods.',
    cost: 'Free attraction · tins add up',
    tags: ['dragonstone', 'hike', 'fishing port'],
  },
  {
    id: 'plentzia',
    chapter: 'basqueEs',
    name: 'Plentzia',
    sub: 'The local secret',
    coords: [43.4049, -2.9472],
    zoom: 12,
    dates: 'Fri 15 – Sat 16 Oct',
    nights: '1',
    leg: 'drive',
    wiki: 'Plentzia',
    wikiExtra: ['Vizcaya Bridge'],
    desc: 'Not touristy, very good, and only thirty minutes from Bilbao. A quiet estuary beach town where the metro from the big city ends. The kind of place the plan exists for.',
    annette: 'Definitely visit Plentzia — not touristy, very good, 30 min drive to Bilbao.',
    highlights: [
      { title: 'Plentzia old town & ría', url: maps('Plentzia casco viejo'), note: 'beachfront pintxos, no menu in English', cost: 'pintxos €15–25 pp' },
      { title: 'Getxo pintxos & tortillas — the local list', url: 'food.html#ll-pintxos-getxo', note: 'Algorta, Neguri and Las Arenas picks from the insider list, all 15 min down the coast', cost: '' },
      { title: 'Vizcaya Bridge (Puente Colgante)', url: maps('Puente de Vizcaya Portugalete'), note: 'UNESCO hanging transporter bridge on the way into Bilbao — ride the gondola across', cost: 'crossing ~€0.55, walkway ~€10' },
    ],
    booking: 'Nothing to book.',
    cost: 'Cheapest night of the trip: rooms €60–90',
    tags: ['local', 'beach', 'quiet'],
  },
  {
    id: 'bilbao',
    chapter: 'basqueEs',
    name: 'Bilbao',
    sub: 'Puerto Viejo + the Etxebarri pilgrimage',
    coords: [43.263, -2.935],
    zoom: 11,
    dates: 'Sat 16 Oct',
    nights: '1',
    leg: 'drive',
    wiki: 'Bilbao',
    wikiExtra: ['Guggenheim Museum Bilbao', 'Casco Viejo, Bilbao'],
    desc: 'Close out the coast run in the big city. Go to the Puerto Viejo in Getxo — lots of people go there, it’s great. El Corte Inglés is the high-end mall for cheese, clothes and anything else worth hauling home. And if you can get a booking, Asador Etxebarri in Axpe (an hour inland) is one of the best restaurants on earth — it slots neatly between here and Rioja on the 17th.',
    annette: 'In Bilbao go to Puerto Viejo — lots of people go there, it’s great. Stuart says: Etxebarri. El Corte Inglés for cheese and clothes and anything else.',
    highlights: [
      { title: 'The local list — 277 Bilbao & Getxo spots', url: 'food.html#local-list', note: 'the insider list on the food tour: pintxos, the tortilla league, txuleta, vermouth, cheesecake', cost: '' },
      { title: 'Asador Etxebarri', url: 'https://www.asadoretxebarri.com/', note: 'Axpe, ~50 min south — everything over the grill, world top-10; on the way to Rioja', cost: 'tasting ~€290 pp + wine' },
      { title: 'Puerto Viejo, Algorta (Getxo)', url: maps('Puerto Viejo Algorta Getxo'), note: 'stacked white fishing quarter full of txakoli bars', cost: 'pintxos €15–30 pp' },
      { title: 'Guggenheim Bilbao', url: 'https://www.guggenheim-bilbao.eus/en', note: 'if the weather turns', cost: '~€18' },
      { title: 'El Corte Inglés Gran Vía', url: maps('El Corte Ingles Gran Via Bilbao'), note: 'cheese, clothes, tins — the haul-home stop', cost: '—' },
      { title: 'Casco Viejo & Plaza Nueva', url: maps('Plaza Nueva Bilbao'), note: 'the Seven Streets — pintxos under the arcades', cost: 'pintxos €15–30 pp' },
      { title: 'Ribera Market', url: maps('Mercado de la Ribera Bilbao'), note: 'Europe’s biggest covered market, on the river edge of the old town', cost: 'free to wander' },
      { title: 'Artxanda funicular', url: maps('Funicular de Artxanda Bilbao'), note: 'the city-in-a-bowl panorama', cost: '~€2 each way' },
    ],
    booking: 'Etxebarri: reservations open on the 1st of each month for ~2 months ahead and vanish in minutes — set an alarm and try for Sun 17 Oct lunch.',
    cost: 'Hotels €100–160/night · Etxebarri ~€350 pp all-in if you get in',
    tags: ['city', 'Etxebarri', 'shopping'],
  },
  {
    id: 'haro',
    chapter: 'rioja',
    name: 'Haro & Tirgo',
    sub: 'Into the wine',
    coords: [42.576, -2.846],
    zoom: 11,
    dates: 'Sun 17 Oct',
    nights: '1',
    leg: 'drive',
    wiki: 'Haro, La Rioja',
    wikiExtra: ['Briones', 'Laguardia, Álava'],
    desc: 'South from Bilbao into a different Spain — dry, historic, and stupid not to visit given it’s the top wine region in the country. The food flips too: lamb, chorizo, lentils, chickpeas. Base around Haro and Tirgo.',
    annette: 'Historically top wine regions in Spain, stupid not to go. Different to Basque country — this is dry. Eat lamb, chorizo, lentils, chickpeas. La Vieja Bodega: so good, people literally fly to eat here.',
    highlights: [
      { title: 'La Vieja Bodega, Casalarreina', url: maps('La Vieja Bodega Casalarreina'), note: 'the fly-in-for-it traditional Spanish one — 10 min from Haro', cost: '€45–65 pp' },
      { title: 'Barrio de la Estación, Haro', url: maps('Barrio de la Estacion Haro'), note: 'highest concentration of century-old wineries on earth: López de Heredia, Muga, La Rioja Alta…', cost: 'tours/tastings €15–40' },
      { title: 'Lamb chops al sarmiento', url: maps('asador Haro'), note: 'grilled over vine cuttings — any asador in town', cost: '€25–40 pp' },
      { title: 'Vivanco Museum of Wine Culture, Briones', url: maps('Museo Vivanco Briones'), note: 'the best wine museum in Spain, under a hilltop village', cost: '~€16.5' },
      { title: 'Laguardia', url: maps('Laguardia Alava'), note: 'walled medieval wine town riddled with cellars — 20 min east', cost: 'free to wander' },
    ],
    booking: 'Winery tours must be pre-booked on their sites (English tours limited — book a week+ ahead). La Vieja Bodega: reserve.',
    cost: 'Hotels €80–130/night · winery day €40–80 pp · bottles from €10 at the door',
    tags: ['rioja', 'wine'],
  },
  {
    id: 'ezcaray',
    chapter: 'rioja',
    name: 'Ezcaray',
    sub: 'The long Michelin lunch',
    coords: [42.3251, -3.0087],
    zoom: 12,
    dates: 'Mon 18 Oct',
    nights: '1',
    leg: 'drive',
    wiki: 'Ezcaray',
    wikiExtra: ['Monasteries of San Millán de la Cogolla'],
    desc: 'A medieval mountain town — the "castles" feel of the Spanish leg. The play: Hotel Echaurren, a Michelin-star place that is somehow down to earth and family owned, with the most excellent croquettes on the planet. Lunch takes 4–5 hours. Walk the town and river after, go home, pass out.',
    annette: 'Have a big lunch — the Michelin one takes 4–5 hours. Walk around the town and river after lunch, go home and pass out. Day after, head to Casa Masip — more traditional, more reasonable.',
    highlights: [
      { title: 'Echaurren (El Portal)', url: 'https://echaurren.com/en/', note: 'Relais & Châteaux, family-run; the croquettes live in the casual Tradición room', cost: 'tasting €150–200 pp · Tradición ~€60–80' },
      { title: 'Hotel Casa Masip', url: maps('Casa Masip Ezcaray'), note: 'the more traditional, more reasonable follow-up meal', cost: 'menu €35–50 pp' },
      { title: 'Ezcaray old town & river walk', url: maps('Ezcaray plaza'), note: 'the post-lunch pass-out lap', cost: 'free' },
      { title: 'San Millán monasteries (Yuso & Suso)', url: maps('Monasterio de Yuso San Millan de la Cogolla'), note: 'UNESCO pair 30 min away — where written Spanish was born', cost: 'tour ~€8' },
    ],
    booking: 'El Portal: book the Mon 18 Oct lunch 2–4 weeks out (website). Staying at Echaurren pairs the room with the lunch — worth it.',
    cost: 'Echaurren rooms €120–200/night · the big lunch €80–200 pp',
    tags: ['michelin', 'medieval', 'croquettes'],
  },
  {
    id: 'bamberg',
    chapter: 'franconia',
    name: 'Bamberg',
    sub: 'The grand finale — smoked beer, then home',
    coords: [49.8917, 10.8917],
    zoom: 6,
    dates: 'Tue 19 – Thu 21 Oct',
    nights: '2 (minimum)',
    leg: 'fly',
    wiki: 'Bamberg',
    wikiExtra: ['Bamberg Cathedral', 'Altenburg (Bamberg)'],
    desc: 'Moved to the end so it no longer fights the route: Tuesday 19th drive Ezcaray → Bilbao (~1 h), drop the car at the airport, fly to Frankfurt or Munich and train to Bamberg (Nuremberg is the closest airport, 40 min away). Two full nights minimum in the medieval, UNESCO-listed beer capital — nine breweries in one small town — as the last stop before heading home. Rollercoasters: the closest parks are Freizeit-Land Geiselwind (~45 min) and Erlebnispark Schloss Thurn (~30 min), but in mid-October both mostly open weekends/Bavarian holidays only, so check calendars before promising anyone; Germany’s big-league coasters (Europa-Park) are 4 h away and don’t fit.',
    annette: 'Three nights in each place is more than plenty. A night in each town, max two.',
    highlights: [
      { title: 'Schlenkerla brewery tavern', url: maps('Schlenkerla Bamberg'), note: 'the classic Rauchbier (smoked beer) cellar since 1405 — order the Zwiebel (beer-braised stuffed onion)', cost: 'beer + meal ~€20–30 pp' },
      { title: 'Brauerei Spezial', url: maps('Brauerei Spezial Bamberg'), note: 'the OTHER smoked beer — gentler than Schlenkerla, all locals, no queue', cost: 'beer ~€3.50' },
      { title: 'Mahrs Bräu', url: maps('Mahrs Brau Bamberg'), note: 'ask for "aU" (ungespundet) — routinely called one of the best beers in the world', cost: 'beer ~€3.50' },
      { title: 'Fässla & Klosterbräu', url: maps('Brauerei Fassla Bamberg'), note: 'round out the crawl: Fässla opposite Spezial, Klosterbräu the oldest in town', cost: 'beer ~€3.50 each' },
      { title: 'Spezial-Keller beer garden', url: maps('Spezial-Keller Bamberg'), note: 'up the hill — smoked beer with the whole old town at your feet', cost: 'beer + snack €10–15' },
      { title: 'Altes Rathaus & Altstadt', url: maps('Altes Rathaus Bamberg'), note: 'the old town hall on its own island — the postcard shot', cost: 'free' },
      { title: 'Bamberg Cathedral & Domplatz', url: maps('Bamberger Dom'), note: 'the imperial cathedral with the Bamberg Horseman; Rose Garden of the Neue Residenz next door', cost: 'free' },
      { title: 'Altenburg castle & Klein Venedig', url: maps('Altenburg Bamberg'), note: 'hilltop castle above town, then the fishermen’s houses along the Regnitz at dusk', cost: 'free' },
      { title: 'Freizeit-Land Geiselwind', url: maps('Freizeit-Land Geiselwind'), note: 'the rollercoaster option, ~45 min east — October opening is weekends/holidays only, check first', cost: '~€30 pp' },
    ],
    booking: 'Bilbao→Frankfurt/Munich hop: book with the long-haul. Bamberg hotels fill on weekends — book a few weeks out. Rollercoaster day: check the Geiselwind and Schloss Thurn October calendars before building the day around them.',
    cost: 'Hotels €90–140/night · Bilbao→Germany flight ~€80–200 pp · beers ~€3.50 (the cheapest round of the trip)',
    tags: ['grand finale', 'medieval', 'beer', 'min 2 nights'],
  },
  {
    id: 'home',
    chapter: 'epilogue',
    name: 'Bamberg → Frankfurt → Sydney',
    sub: 'Train to the hub, fly out',
    coords: [50.0379, 8.5622],
    zoom: 6,
    dates: 'Thu 21 – Fri 22 Oct',
    nights: '1 (airport)',
    leg: 'train',
    wiki: 'Frankfurt Airport',
    wikiExtra: ['Frankfurt'],
    desc: 'Thursday 21st: ICE from Bamberg to Frankfurt Airport (~2.5 h, direct or one change), overnight at the airport. Friday 22nd: fly Frankfurt → Sydney, landing Sunday 24 October — clear of the Monday 25th deadline. The car went back in Bilbao on the 19th, so the cheese, txakoli and tins ride home in checked bags — pack a soft duffel for the haul. October rule the whole way: pack for all weather — gumboots and a raincoat for chilly nights, summer kit for the surf towns.',
    annette: 'It will be chilly in October nights — take gumboots and a raincoat. Make sure accommodation has parking for the car you rent.',
    highlights: [
      { title: 'Frankfurt Airport (FRA)', url: maps('Frankfurt Airport'), note: 'long-haul hub — direct one-stop routes to Sydney via Singapore/Doha', cost: 'FRA→SYD return leg priced in the long-haul' },
      { title: 'DB ICE Bamberg → Frankfurt Flughafen', url: 'https://int.bahn.de/en', note: 'book a Sparpreis fare a few weeks out — seat reservations recommended with luggage', cost: '€30–70 pp' },
    ],
    booking: 'Book the long-haul as Paris in / Frankfurt out (open-jaw) so no leg backtracks. Confirm the rental France pickup → Bilbao drop fee before locking the car.',
    cost: 'Airport hotel €90–140 · ICE €30–70 pp',
    tags: ['fly home', 'packing', 'land Sun 24 Oct'],
  },
];
