// COB SHOPPING — boutiques, Basque labels and Barbour hunting, in route order.
// Same shape as food/activities: qs = 3 Commons image queries, town used as image fallback.

const maps = (q) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;

export const SHOPS = [
  {
    name: 'Golden Triangle & Rue Sainte-Catherine',
    town: 'Bordeaux',
    date: 'Wed 6 – Thu 7 Oct',
    url: maps('Triangle d\'Or Bordeaux boutiques'),
    qs: ['Rue Sainte-Catherine Bordeaux', 'Cours de l\'Intendance Bordeaux', 'Galeries Lafayette'],
    note: 'The Triangle d’Or holds the designer flagships; Rue Sainte-Catherine is Europe’s longest shopping street for everything else. Galeries Lafayette anchors the middle.',
    cost: '€€–€€€€',
    badge: 'boutique fashion',
  },
  {
    name: 'Barbour hunting, France leg',
    town: 'Bordeaux & Biarritz',
    date: 'any France day',
    url: maps('Barbour Bordeaux'),
    qs: ['waxed jacket', 'Barbour jacket', 'menswear shop interior'],
    note: 'Barbour sells in France through multi-brand menswear dealers rather than own stores — both Bordeaux’s centre and Biarritz (with its British golf-and-surf heritage) have stockists; the Maps link finds the current ones. October rain is exactly what a waxed Bedale is for.',
    cost: 'wax jackets €250–450',
    badge: 'BARBOUR',
  },
  {
    name: 'Burberry hunting',
    town: 'Paris → Bordeaux → Biarritz → Bilbao',
    date: 'along the way',
    url: 'https://stores.burberry.com/',
    qs: ['Burberry trench coat', 'Allées de Tourny Bordeaux', 'luxury boutique interior'],
    note: 'No standalone Burberry stores on the coast — the flagships are in Paris (night one, if you land early enough). En route it sells through multi-brand stockists: Rainbow at 30 Allées de Tourny in Bordeaux, The Corner on Avenue de la Reine Victoria in Biarritz, and in Bilbao both El Corte Inglés and the Embassy boutique carry it. Check the official store locator for current stock.',
    cost: 'scarves ~€500 · trench €2,000+',
    badge: 'BURBERRY',
  },
  {
    name: 'Surf-brand outlets',
    town: 'Hossegor & Capbreton',
    date: 'Fri 8 – Sat 9 Oct',
    url: maps('surf shop outlet Soorts-Hossegor'),
    qs: ['Hossegor surfers beach', 'surfboards', 'Capbreton beach'],
    note: 'The European surf industry is headquartered here — Quiksilver, Billabong, Rip Curl and co. run outlet stores between Hossegor and Capbreton. Comp weekend brings pop-ups too.',
    cost: 'outlet tees/hoodies €20–60',
    badge: 'outlets',
  },
  {
    name: 'Basque linen: Jean-Vier & Tissage de Luz',
    town: 'Bayonne / Saint-Jean-de-Luz',
    date: 'Sun 10 – Tue 12 Oct',
    url: maps('Jean-Vier Saint-Jean-de-Luz'),
    qs: ['Saint-Jean-de-Luz rue Gambetta', 'espadrilles', 'Saint-Jean-de-Luz houses'],
    note: 'The striped Basque linen you’ll see on every table, from the two classic houses. Tablecloths, tea towels, deck chairs — the useful souvenir.',
    cost: 'tea towels ~€15 · tablecloths €40–120',
    badge: 'Basque classic',
  },
  {
    name: 'A proper French beret',
    town: 'Bayonne',
    date: 'Sun 10 – Mon 11 Oct',
    url: maps('beret shop Bayonne'),
    qs: ['man wearing beret', 'txapela', 'Bayonne cathedral France'],
    note: 'The real ones come from Laulhère (weaving since 1840) and sell through Bayonne and Biarritz hatters. One each for the road-trip photos.',
    cost: '€40–90',
    badge: 'icon',
  },
  {
    name: 'Biarritz boutiques, Place Clemenceau',
    town: 'Biarritz',
    date: 'Sun 10 – Mon 11 Oct',
    url: maps('Place Clemenceau Biarritz boutiques'),
    qs: ['Hôtel du Palais Biarritz', 'Biarritz Sainte-Eugénie', 'Biarritz Grande Plage'],
    note: 'The fancy-shops part Annette mentioned: French and Basque labels around Place Clemenceau and Avenue Édouard VII, plus 64 — the Basque-country brand — for hoodies with the region’s postcode.',
    cost: '€€–€€€€ · 64 tees ~€35',
    badge: 'boutique fashion',
  },
  {
    name: 'Espadrilles, made to order',
    town: 'Saint-Jean-de-Luz',
    date: 'Tue 12 Oct',
    url: maps('espadrilles Saint-Jean-de-Luz'),
    qs: ['espadrilles', 'espadrille maker Basque', 'Saint-Jean-de-Luz rue Gambetta'],
    note: 'Rue Gambetta’s makers still hand-stitch espadrilles — pick sole and canvas and they’re done while you eat macarons.',
    cost: '€25–60',
    badge: 'artisan',
  },
  {
    name: 'Loreak Mendian & the Gros quarter',
    town: 'San Sebastián',
    date: 'Tue 12 – Thu 14 Oct',
    url: maps('Loreak Mendian San Sebastian'),
    qs: ['San Sebastian Gros', 'clothing boutique interior', 'Zurriola beach'],
    note: 'San Seb’s own label — graphic knits and surf-adjacent basics — plus the independent boutiques of the Gros surf quarter behind Zurriola beach.',
    cost: 'tees €40–70 · knits €90–150',
    badge: 'Basque label',
  },
  {
    name: 'Balenciaga Museum shop',
    town: 'Getaria',
    date: 'Fri 15 Oct',
    url: maps('Cristobal Balenciaga Museoa Getaria'),
    qs: ['Balenciaga dress museum', 'Cristobal Balenciaga Museoa', 'Getaria Gipuzkoa'],
    note: 'You can’t buy couture, but the museum shop’s books, scarves and prints are the classiest souvenir on the route — from the fishing village that produced fashion’s greatest cutter.',
    cost: 'scarves/books €20–80 · museum ~€10',
    badge: 'fashion pilgrimage',
  },
  {
    name: 'El Corte Inglés Gran Vía',
    town: 'Bilbao',
    date: 'Mon 18 Oct',
    url: maps('El Corte Ingles Gran Via Bilbao'),
    qs: ['El Corte Ingles Bilbao', 'department store menswear', 'Gran Via Bilbao'],
    note: 'Annette’s haul-home stop, and the reliable Barbour bet in Spain — the menswear floor usually carries the core waxed and quilted range. Cheese, tins and txakoli in the food hall on the way out.',
    cost: 'Barbour range €130–450',
    badge: 'BARBOUR · Annette pick',
  },
  {
    name: 'Casco Viejo independents',
    town: 'Bilbao',
    date: 'Mon 18 Oct',
    url: maps('Casco Viejo Bilbao tiendas'),
    qs: ['Casco Viejo Bilbao street', 'Plaza Nueva Bilbao', 'boutique shop window'],
    note: 'The Seven Streets hide Bilbao’s independents — Basque streetwear, txapela (beret) shops and old-school gentleman’s outfitters between the pintxos bars.',
    cost: '€–€€€',
    badge: 'boutique fashion',
  },
  {
    name: 'Cellar-door Rioja',
    town: 'Haro',
    date: 'Tue 19 Oct',
    url: maps('Barrio de la Estacion Haro'),
    qs: ['Rioja wine bottles', 'Lopez de Heredia', 'wine shop Haro'],
    note: 'The shopping finale: reservas and gran reservas straight from the Barrio de la Estación bodegas at cellar-door prices. Buy the boot-load on the last drive — no more nights to lug it through.',
    cost: 'bottles €10–40 · gran reserva €40+',
    badge: 'liquid souvenirs',
  },
];
