// COB FOOD TOUR — every meal worth planning around, in route order.
// Mix of Annette's picks, Stuart's picks, and the Michelin heavy-hitters along the way.
// stars: Michelin stars (0 = none needed), q: image search query for the thumbnail.

const maps = (q) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`;

export const COURSES = [
  {
    name: 'Oyster cabanes of Marennes-Oléron',
    stars: 0,
    town: 'South of Royan',
    date: 'Tue 5 Oct',
    url: maps('degustation huitres Marennes-Oléron'),
    qs: ['Marennes Oléron oysters', 'oyster farming Charente-Maritime', 'huitres cabane ostréicole'],
    note: 'The baseline plate. Huge, fresh, flavour-loaded — eaten at the producer’s shack on the channel.',
    cost: 'dozen €12–20',
    badge: 'Annette pick',
  },
  {
    name: 'La Tupina',
    stars: 0,
    town: 'Bordeaux',
    date: 'Wed 6 – Thu 7 Oct',
    url: maps('La Tupina Bordeaux'),
    qs: ['confit de canard', 'Bordeaux Saint-Michel', 'cuisine du Sud-Ouest'],
    note: 'The old-guard institution of southwest France: duck fat, open fire, shirt-straining portions. The Bordeaux big lunch.',
    cost: '€50–80 pp',
    badge: 'classic',
  },
  {
    name: 'Port de Capbreton seafood shacks',
    stars: 0,
    town: 'Capbreton & Hossegor',
    date: 'Fri 8 – Sat 9 Oct',
    url: maps('degustation huitres Capbreton port'),
    qs: ['Capbreton port', 'Capbreton estacade', 'moules frites'],
    note: 'Oysters between surf heats — and mussels the size of your head.',
    cost: '€20–35 pp',
    badge: 'Annette pick',
  },
  {
    name: 'Hétéroclito',
    stars: 0,
    town: 'Bayonne',
    date: 'Sun 10 or Mon 11 Oct',
    url: maps('Heteroclito restaurant Bayonne'),
    qs: ['Bayonne Nive', 'Petit Bayonne', 'jambon de Bayonne'],
    note: 'THE Annette table. Book ahead, sit outside, time it for sunset.',
    cost: 'dinner €40–60 pp',
    badge: 'Annette pick · book ahead',
  },
  {
    name: 'Les Halles de Biarritz + Bar Jean',
    stars: 0,
    town: 'Biarritz',
    date: 'Sun 10 – Mon 11 Oct',
    url: maps('Bar Jean Biarritz'),
    qs: ['Les Halles Biarritz', 'Biarritz Grande Plage', 'côte de boeuf grillée'],
    note: 'Graze the market in the morning, then txuleta at Bar Jean next door — pricey but good, like fancy.',
    cost: 'txuleta €50–70 pp',
    badge: 'Annette pick',
  },
  {
    name: 'Grillerie du Port',
    stars: 0,
    town: 'Saint-Jean-de-Luz',
    date: 'Tue 12 Oct, lunch',
    url: maps('Grillerie du Port Saint-Jean-de-Luz'),
    qs: ['Saint-Jean-de-Luz port', 'grilled sardines', 'Saint-Jean-de-Luz houses'],
    note: 'Whole sardines and tuna over coals, on the quay of the prettiest port in France. Macarons from Maison Adam after.',
    cost: '€20–35 pp',
    badge: 'last lunch in France',
  },
  {
    name: 'Old-town pintxos crawl (Bar Néstor → La Cuchara → Gandarias)',
    stars: 0,
    town: 'San Sebastián',
    date: 'Tue 12 – Thu 14 Oct',
    url: maps('Bar Nestor San Sebastian'),
    qs: ['pintxos San Sebastian', 'Parte Vieja San Sebastian', 'tortilla de patatas'],
    note: 'Bar Néstor for the tomato salad and tortilla (put your name down early — this is the tomato-salad commandment fulfilled), then work outward one pintxo and one txakoli per bar.',
    cost: '€30–50 pp per crawl',
    badge: 'tomato salads',
  },
  {
    name: 'The clam stop — txirlak a la marinera',
    stars: 0,
    town: 'San Sebastián',
    date: 'Tue 12 – Thu 14 Oct',
    url: maps('Restaurante Gandarias San Sebastian'),
    qs: ['almejas a la marinera', 'clams white wine sauce', 'La Rampa San Sebastian port'],
    note: 'Basque clams come in salsa verde — white wine, garlic, parsley, clam juice — and Gandarias in the old town is the name for them (it’s already on the pintxos crawl; sit down and order the ración). Alternates: Bare Bare for clams and razor clams, or La Rampa on the port with a terrace over the fishing boats. Bread for the sauce is not optional.',
    cost: 'ración €15–25',
    badge: 'clam mission',
  },
  {
    name: 'La Viña — burnt Basque cheesecake',
    stars: 0,
    town: 'San Sebastián',
    date: 'any day, twice',
    url: maps('La Vina San Sebastian cheesecake'),
    qs: ['Basque burnt cheesecake', 'cheesecake slice', 'Parte Vieja San Sebastian street'],
    note: 'Where the burnt cheesecake was invented. Best cheesecake on the planet, per Annette. Non-negotiable.',
    cost: 'slice ~€6',
    badge: 'Annette pick',
  },
  {
    name: 'Arzak',
    stars: 3,
    town: 'San Sebastián',
    date: 'Tue 12 – Thu 14 Oct',
    url: maps('Restaurante Arzak San Sebastian'),
    qs: ['Arzak', 'nueva cocina vasca', 'San Sebastian Gros'],
    note: 'Father-and-daughter three-star that started New Basque Cuisine. The splash-out option if Etxebarri doesn’t come through.',
    cost: 'tasting ~€310 pp',
    badge: '★★★ option',
  },
  {
    name: 'Mountain sagardotegi (cider house)',
    stars: 0,
    town: 'Hills above San Sebastián',
    date: 'one evening, 12–14 Oct',
    url: maps('sagardotegia Astigarraga'),
    qs: ['sagardotegia', 'Basque cider txotx', 'sidra natural'],
    note: 'Cod omelette, txuleta, cheese with quince, catch-your-own cider from the barrel. Ask locals, drive to the most remote one. Confirm October opening — classic season is Jan–Apr.',
    cost: 'set feast €40–50 pp',
    badge: 'Annette pick · call ahead',
  },
  {
    name: 'Bodegón Asador Joxe Mari',
    stars: 0,
    town: 'Orio',
    date: 'Fri 15 Oct, lunch',
    url: maps('Bodegon Joxe Mari Orio'),
    qs: ['Orio Gipuzkoa', 'besugo a la parrilla', 'Orio river'],
    note: 'Stuart’s call: whole wild fish over coals on the riverfront. Sold by weight — confirm the price when ordering.',
    cost: '€50–80 pp with wine',
    badge: 'Stuart pick',
  },
  {
    name: 'Elkano',
    stars: 1,
    town: 'Getaria (10 min from Orio)',
    date: 'Fri 15 Oct — alternative',
    url: maps('Elkano Getaria'),
    qs: ['Getaria Gipuzkoa', 'turbot', 'Getaria port'],
    note: 'The most famous grilled turbot on earth — one star, whole fish over coals, same tradition as Joxe Mari dialled to eleven. Pick one of the two.',
    cost: 'turbot ~€150–200 pp',
    badge: '★ option',
  },
  {
    name: 'Asador Etxebarri',
    stars: 1,
    town: 'Axpe (1 h from Bilbao)',
    date: 'target Tue 19 Oct, lunch',
    url: 'https://www.asadoretxebarri.com/',
    qs: ['Asador Etxebarri', 'Axpe Atxondo', 'Anboto'],
    note: 'Everything — even the ice cream — touched by wood fire. Perennial world top-5. Reservations open the 1st of the month and vanish in minutes: set the alarm.',
    cost: 'tasting ~€290 pp + wine',
    badge: '★ · Stuart pick · alarm required',
  },
  {
    name: 'Azurmendi',
    stars: 3,
    town: 'Larrabetzu (15 min from Bilbao)',
    date: 'Mon 18 Oct — fallback',
    url: maps('Azurmendi Larrabetzu'),
    qs: ['Larrabetzu', 'txakoli vineyard', 'Bizkaia countryside'],
    note: 'Eneko Atxa’s three-star eco-temple in the txakoli vines. The backup splash-out if the Etxebarri alarm fails.',
    cost: 'tasting ~€250 pp',
    badge: '★★★ option',
  },
  {
    name: 'Puerto Viejo txakoli bars',
    stars: 0,
    town: 'Algorta, Getxo',
    date: 'Sun 17 – Mon 18 Oct',
    url: maps('Puerto Viejo Algorta Getxo'),
    qs: ['Puerto Viejo Algorta', 'Getxo coast', 'txakoli pouring'],
    note: 'Annette’s Bilbao order: the stacked white fishing quarter, anchovies and txakoli poured from height.',
    cost: '€15–30 pp',
    badge: 'Annette pick',
  },
  {
    name: 'La Vieja Bodega',
    stars: 0,
    town: 'Casalarreina, Rioja',
    date: 'Tue 19 Oct, dinner',
    url: maps('La Vieja Bodega Casalarreina'),
    qs: ['Casalarreina', 'Rioja wine cellar barrels', 'La Rioja vineyards'],
    note: 'Traditional Spanish cooking in a 16th-century cellar — so good people literally fly in to eat here. The food flips: lamb, chorizo, lentils, chickpeas.',
    cost: '€45–65 pp',
    badge: 'Annette pick · book',
  },
  {
    name: 'Lamb chops al sarmiento',
    stars: 0,
    town: 'Haro',
    date: 'Tue 19 Oct',
    url: maps('asador Haro chuletillas al sarmiento'),
    qs: ['chuletillas al sarmiento', 'Haro La Rioja', 'lamb chops grill'],
    note: 'Baby lamb chops flash-grilled over burning vine cuttings — Rioja’s signature smoke. Any asador in town.',
    cost: '€25–40 pp',
    badge: 'regional rite',
  },
  {
    name: 'Echaurren — El Portal',
    stars: 2,
    town: 'Ezcaray',
    date: 'Wed 20 Oct, lunch',
    url: 'https://echaurren.com/en/',
    qs: ['Ezcaray', 'croquetas', 'Ezcaray plaza'],
    note: 'The hectic-but-humble family two-star. The 4–5 hour lunch. The most excellent croquettes on the planet live in the casual Tradición room. Walk the river after, go home, pass out.',
    cost: 'tasting €150–200 · Tradición €60–80',
    badge: '★★ · Annette pick · book 2–4 wks',
  },
  {
    name: 'Hotel Casa Masip',
    stars: 0,
    town: 'Ezcaray',
    date: 'Wed 20 or Thu 21 Oct',
    url: maps('Casa Masip Ezcaray'),
    qs: ['Ezcaray Rio Oja', 'Ezcaray street', 'menu del dia Spain'],
    note: 'The day-after meal: more traditional, more reasonable, exactly what the body wants after El Portal.',
    cost: 'menu €35–50 pp',
    badge: 'Annette pick',
  },
];
